version: '3'

services:
  tor:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      HOSTNAME: $HOSTNAME 
      PRIVATE_KEY_HEX: $PRIVATE_KEY_HEX
      PUBLIC_KEY_HEX: $PUBLIC_KEY_HEX
      SERVICE_PORT: $SERVICE_PORT
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
